#cloud-config

repo_update: true
repo_upgrade: all

write_files:
  - path: /etc/cluster_machines.txt
    content: |
      ${cluster_machines}

  - path: /etc/self_private_ip.txt
    content: |
      ${self_private_ip}

  - path: /etc/region.txt
    content: |
      ${region}


runcmd:
 - echo bar

